app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index)
]

postgresqltest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'), name='app')
]

app/models.py
from django.db import models

class Film(models.Model):
    G_ACTION = "ACC"
    G_COMEDY = "COM"
    G_DOC = "DOC"
    G_SCIFI = "SCI"
    G_HORROR = "HORR"
    G_ANIMATED = "ANIM"
    G_DRAMA = "DRAM"
    GENRE_CHOICES = [
        (G_ACTION, "Acción"),
        (G_COMEDY, "Comedia"),
        (G_DOC, "Documental"),
        (G_SCIFI, "Ciencia Ficción"),
        (G_HORROR, "Horror"),
        (G_ANIMATED, "Animada"),
        (G_DRAMA, "Drama")
    ]
    name = models.CharField("Nombre", max_length=50)
    release_date = models.DateField("Fecha de estreno")
    genre = models.CharField("Género", max_length=5, choices=GENRE_CHOICES, blank=True)
    RATING_CHOICES = [
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    ]
    rating = models.SmallIntegerField("Calificación", choices=RATING_CHOICES, blank=True, null=True)
    def __str__(self) -> str:
        return f"{self.name} ({self.release_date.year})"

app/views.py
from django.shortcuts import render
from .models import Film


def index(request):
    context = {"films": Film.objects.all()}
    return render(request, "index.html", context=context)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	{% block content %}
	{% endblock %}
</body>
</html>

app/templates/index.html
{% include "./base.html" %}
{% block content %}
<h1>Index</h1>
{% if films %}
	<table>
		<thead>
			<tr>
				<td>Nombre</td>
				<td>Fecha de lanzamiento</td>
				<td>Género</td>
				<td>Calificación</td>
			</tr>
		</thead>
		<tbody>
		{% for film in films %}
			<tr>
				<td>{{ film.name }}</td>
				<td>{{ film.release_date|date:"d/m/Y" }}</td>
				<td>{{ film.get_genre_display|default:"Sin género" }}</td>
				<td>{{ film.rating|default_if_none:"No calificado" }}</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
{% else %}
	<h2>Aun no hay películas u_u</h2>
{% endif %}
{% endblock %}